#!/usr/bin/env python3
"""Convert an animated GIF into C source for the ESP32-C6 display firmware.

Emits <out>.h / <out>.cpp containing, as const arrays in flash:

  <P>_PALETTE[]   RGB565 colour table (host byte order, <= 256 entries)
  <P>_BASE[]      8-bit palette indices for the whole first frame (w * h)
  <P>_PATCH[][]   8-bit palette indices for the rectangle that differs between
                  frames, one entry per *unique* frame (patch_w * patch_h each)
  <P>_SEQ[]       which patch to draw at each animation step

Pixel-identical frames are stored once. The firmware draws the base frame
once, then only re-draws the patch rectangle every tick, so per-frame SPI
traffic is small and there is no flicker.

Usage:
    python3 tools/gif2header.py assets/plane.gif src/plane_gif_data PLANE

Requires Pillow:  pip install pillow
"""
import sys
from pathlib import Path

from PIL import Image, ImageSequence


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def fmt_bytes(data, per_line=32) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        lines.append("  " + ",".join(str(b) for b in data[i : i + per_line]) + ",")
    return "\n".join(lines)


def main(argv):
    if len(argv) != 4:
        print(__doc__)
        return 2
    src, out_base, prefix = Path(argv[1]), Path(argv[2]), argv[3]

    im = Image.open(src)
    w, h = im.size
    # ImageSequence.Iterator yields the same Image object seeked to each frame,
    # so copy/convert each one immediately instead of collecting the iterator.
    frames, durations = [], []
    for f in ImageSequence.Iterator(im):
        frames.append(f.convert("RGB"))
        durations.append(f.info.get("duration", 100))

    # Global palette across all frames.
    palette: dict[tuple[int, int, int], int] = {}
    for f in frames:
        for c in f.getdata():
            if c not in palette:
                palette[c] = len(palette)
    if len(palette) > 256:
        print(f"error: {len(palette)} colours, max 256. Quantise the gif first.")
        return 1

    indexed = [[palette[c] for c in f.getdata()] for f in frames]

    # Bounding box of every pixel that differs from frame 0 in any frame.
    x0, y0, x1, y1 = w, h, 0, 0
    for fr in indexed[1:]:
        for i, (a, b) in enumerate(zip(indexed[0], fr)):
            if a != b:
                x, y = i % w, i // w
                x0, y0 = min(x0, x), min(y0, y)
                x1, y1 = max(x1, x + 1), max(y1, y + 1)
    if x1 <= x0:  # static image: degenerate 1x1 patch
        x0, y0, x1, y1 = 0, 0, 1, 1
    pw, ph = x1 - x0, y1 - y0

    # Unique patches + play sequence.
    patches: list[bytes] = []
    seq: list[int] = []
    for fr in indexed:
        patch = bytes(fr[y * w + x] for y in range(y0, y1) for x in range(x0, x1))
        if patch not in patches:
            patches.append(patch)
        seq.append(patches.index(patch))

    frame_ms = durations[0]
    if len(set(durations)) > 1:
        print(f"warning: non-uniform frame durations {durations}, using {frame_ms} ms")

    pal565 = [rgb565(*c) for c in palette]
    base = bytes(indexed[0])
    total = len(pal565) * 2 + len(base) + len(patches) * pw * ph + len(seq)

    banner = (
        f"// Generated by tools/gif2header.py from {src.as_posix()} -- do not edit.\n"
        f"// {w}x{h}, {len(frames)} steps, {len(patches)} unique frames, "
        f"{len(palette)} colours, patch {pw}x{ph} @ ({x0},{y0}), ~{total} bytes.\n"
    )

    header = f"""{banner}#pragma once

#include <stdint.h>

#define {prefix}_W            {w}
#define {prefix}_H            {h}
#define {prefix}_PATCH_X      {x0}
#define {prefix}_PATCH_Y      {y0}
#define {prefix}_PATCH_W      {pw}
#define {prefix}_PATCH_H      {ph}
#define {prefix}_PALETTE_LEN  {len(pal565)}
#define {prefix}_PATCH_COUNT  {len(patches)}
#define {prefix}_SEQ_LEN      {len(seq)}
#define {prefix}_FRAME_MS     {frame_ms}

extern const uint16_t {prefix}_PALETTE[{prefix}_PALETTE_LEN];
extern const uint8_t  {prefix}_SEQ[{prefix}_SEQ_LEN];
extern const uint8_t  {prefix}_BASE[{prefix}_W * {prefix}_H];
extern const uint8_t  {prefix}_PATCH[{prefix}_PATCH_COUNT][{prefix}_PATCH_W * {prefix}_PATCH_H];
"""

    patch_blocks = ",\n".join("  {\n" + fmt_bytes(p) + "\n  }" for p in patches)
    source = f"""{banner}#include "{out_base.name}.h"

const uint16_t {prefix}_PALETTE[{prefix}_PALETTE_LEN] = {{
{fmt_bytes([f"0x{v:04X}" for v in pal565], 12).replace("'", "")}
}};

const uint8_t {prefix}_SEQ[{prefix}_SEQ_LEN] = {{ {",".join(str(s) for s in seq)} }};

const uint8_t {prefix}_BASE[{prefix}_W * {prefix}_H] = {{
{fmt_bytes(base)}
}};

const uint8_t {prefix}_PATCH[{prefix}_PATCH_COUNT][{prefix}_PATCH_W * {prefix}_PATCH_H] = {{
{patch_blocks}
}};
"""

    out_base.with_suffix(".h").write_text(header)
    out_base.with_suffix(".cpp").write_text(source)
    print(
        f"{src.name}: {w}x{h}, {len(frames)} steps -> {len(patches)} unique frames, "
        f"{len(palette)} colours, patch {pw}x{ph} @ ({x0},{y0}), {frame_ms} ms/frame"
    )
    print(f"flash cost ~{total:,} bytes -> {out_base}.h / {out_base}.cpp")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
