// Generated by tools/gif2header.py from assets/plane.gif -- do not edit.
// 240x180, 6 steps, 3 unique frames, 86 colours, patch 88x79 @ (152,101), ~64234 bytes.
#pragma once

#include <stdint.h>

#define PLANE_W            240
#define PLANE_H            180
#define PLANE_PATCH_X      152
#define PLANE_PATCH_Y      101
#define PLANE_PATCH_W      88
#define PLANE_PATCH_H      79
#define PLANE_PALETTE_LEN  86
#define PLANE_PATCH_COUNT  3
#define PLANE_SEQ_LEN      6
#define PLANE_FRAME_MS     130

extern const uint16_t PLANE_PALETTE[PLANE_PALETTE_LEN];
extern const uint8_t  PLANE_SEQ[PLANE_SEQ_LEN];
extern const uint8_t  PLANE_BASE[PLANE_W * PLANE_H];
extern const uint8_t  PLANE_PATCH[PLANE_PATCH_COUNT][PLANE_PATCH_W * PLANE_PATCH_H];
